"""game_progress

Revision ID: d1f5807b3c80
Revises: bdc94b8235db
Create Date: 2021-11-16 19:37:07.045945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f5807b3c80'
down_revision = 'bdc94b8235db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('progress', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'progress')
    # ### end Alembic commands ###
