export const LOAD_GAME = 'LOAD_GAME';
export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const LOAD_GAME_FAILURE = 'LOAD_GAME_FAILURE';

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_FAILURE = 'SUBMIT_ANSWER_FAILURE';

export const ANSWER_CORRECT = 'ANSWER_CORRECT';
export const ANSWER_WRONG = 'ANSWER_WRONG';
export const ANSWER_HELP = 'ANSWER_HELP';

export const ANSWER_INPUT_CHANGE = 'ANSWER_INPUT_CHANGE';

export const RESET_STYLE = 'RESET_STYLE';
